// pages/index.js

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Write Your Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <div className={styles.center}>
        <h2>Apni Blogging Website</h2>
        <div className={styles.imageContainer}>
          <Image
            src="/profile.png"
            width={200}
            height={200}
            alt="Picture of the author"
            className={styles.image}
          />
        </div>
      </div>

      <div className={styles.pointlistContainer}>
        <h2>Three Awesome Points</h2>
        <ul className={styles.pointlist}>
          <li>
            <Link href="#" className={styles.pointLink}>
              This is an awesome point.
            </Link>
            <p>It contains some text that describes the point.</p>
          </li>
          <li>
            <Link href="#" className={styles.pointLink}>
              This is another awesome point.
            </Link>
            <p>It contains some text that describes this point.</p>
          </li>
          <li>
            <Link href="#" className={styles.pointLink}>
              This is yet another awesome point.
            </Link>
            <p>It contains some text that describes this point.</p>
          </li>
        </ul>
      </div>
    </>
  );
}
